# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_baseingredient_ingredientmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='article',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='platform',
        ),
        migrations.AlterField(
            model_name='baseingredient',
            name='category',
            field=models.CharField(choices=[('BAKING', 'Baking'), ('BREAD', 'Bread'), ('CANNED', 'Canned'), ('DAIRY', 'Dairy'), ('HERB', 'Herb'), ('FROZEN', 'Frozen'), ('FRUIT', 'Fruit'), ('NUT', 'Nut'), ('MEAT', 'Meat'), ('MISC', 'Misc'), ('OTHER', 'Other'), ('SEAFOOD', 'Seafood'), ('SPICE', 'Spice'), ('VEGETABLE', 'Vegetable')], default='OTHER', max_length=255),
        ),
        migrations.AlterField(
            model_name='baseingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
